### ISSUE TITLE
How to get the value of Extended CMU Seasons?

### ISSUE THREAD

**Issue by MAX-OTW** [marialeyvallina/generalized_contrastive_loss#15]
Hello, @marialeyvallina @nicstrisc ，I really appreciate for your work.
I have a question, the Table 6 shows that the result of Extended CMU Seasons of ResNext-GeM-GCL:
Urban:11.1 / 28.7 / 87.4;
Suburban:4.2 / 14.6 / 77.4;
Park:3.1 / 11.1 / 57.7

And the Mean result is :
6.1 / 18.2 / 74.9

Is it weighted in some way? How is it converted?
I am always looking forward to your kind response.
Best regards.

**Comment by marialeyvallina** [comment]
Hi. For both CMU and Oxford it is weighted by the amount of images in each subset. As you can see from the dataset Oxford has 1443 query images in day and 429 in night. The avg is (day_result*1443+night_result*429)/(1443+429). With Extendedcmu is the same but for the amount of images in their respective subsets.
