### ISSUE TITLE
About the Figure 14 in the paper

### ISSUE THREAD

**Issue by MAX-OTW** [marialeyvallina/generalized_contrastive_loss#16]
Hello, @marialeyvallina -The Figure 14(CNN activations) in the paper looks great. Currently I want to try to implement it but I failed. Is it convenient to provide the relevant implementation code?Of course, detailed guidance would be better.
I am always looking forward to your kind response.
Best regards.

**Comment by marialeyvallina** [comment]
For that you need to get the output of the convolutional layer that you want to plot (I normally use the last one, so you would just need to remove the pooling and do a forward).  Then I get the average over the convolution channels and resize with interpolation. 
I do not plan to release this code, as it is trivial.
