### ISSUE TITLE
PCA whitening

### ISSUE THREAD

**Issue by lasuomela** [marialeyvallina/generalized_contrastive_loss#6]
Hi,

Interesting work! I'm excited try the method out in my own research.

But I have a quation regarding the descriptor PCA whitening implementation mentioned in the paper - namely, I couldn't find the implementation in the code. Did I just miss it, or did you not include the implementation in the release?

Thanks!

**Comment by nicstrisc** [comment]
Hi @lasuomela,
we are updating the repository soon, with extra test code and models (for the time being). 
At a later stage, we will also upload the training code.
Cheers,
Nicola

**Comment by lasuomela** [comment]
Okay, thanks a lot!

**Comment by marialeyvallina** [comment]
Hi @lasuomela. The PCA script has been added.
